{% set name = "pycm" %}
{% set version = "7.5.4" %}

package:
   name: "{{ name }}"
   version: "{{ version }}"

source:
   url: http://software.igwn.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
   sha256: 73ef3cfae95c065e36e71d3b99497c1563b054934fe91889724377ba35fb7965

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake >=3.12.0
    - make  # [unix]
    - ctypesgen >=1.0.2
  host:
    - cm >=9.0.1
    - ctypesgen >=1.0.2
    - python
  run:
    - cm >=9.0.1
    - python

test:
  imports:
    - PyCm

about:
  home: "https://git.ligo.org/virgo/virgoapp/PyCm"
  license: "GPL-3.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE"
  summary: "Python binding for the Cm Library"

extra:
  recipe-maintainers:
      - rhyspoulton
      - fcarbogn
