{% set name = "pycm" %}
{% set version = "7.5.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.igwn.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 7a0e8308e224ed34286ae1766b41950e4135b23b67cc741c1bbcb39251f0f51a

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake >=3.12.0
    - make  # [unix]
    - ctypesgen >=1.0.2
  host:
    - cm >=10.3.4
    - ctypesgen >=1.0.2
    - python
  run:
    - cm >=10.3.4
    - python

test:
  imports:
    - PyCm

about:
  home: https://git.ligo.org/virgo/virgoapp/PyCm
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python binding for the Cm Library

extra:
  recipe-maintainers:
    - rhyspoulton
    - fcarbogn
