schema_version: 1

context:
  name: pycm
  version: 7.5.9

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://git.ligo.org/virgo/virgoapp/PyCm/-/archive/${{ version }}/PyCm-${{ version }}.tar.gz
  sha256: 2f29fbe86b7a1a7099049055b18b45de7497f392a9f2d89a366e8d5f4f6aed6e
  patches:
    - 0001-Use-IS_WRITABLE-unary-test.patch

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - cmake >=3.29.0
    - ctypesgen >=1.0.2
    - make
    - pkg-config
  host:
    - cm >=10.3.4
    - ctypesgen >=1.0.2
    - python
  run:
    - python

tests:
  - python:
      imports:
        - PyCm

about:
  summary: Python binding for the Cm Library
  homepage: https://git.ligo.org/virgo/virgoapp/PyCm
  repository: https://git.ligo.org/virgo/virgoapp/PyCm
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
    - erinelizabethseder-virgo
    - fcarbogn
